"""
Build a scooter-rider injury dataset + time series from DC's crash data.

Inputs:
  - data/raw/crash_details_table.csv (local; person-level, no dates --
    fetch it first with `uv run fetch-crash-data`, see fetch_crash_data.py)
  - DDOT "Crashes in DC" ArcGIS FeatureServer (remote, crash-level, has
    REPORTDATE/WARD), queried live and joined on CRIMEID.

Outputs (all written to output/):
  - person_level.csv
  - timeseries_month_severity.csv   (finest grain, ~98% REPORTDATE coverage)
  - timeseries_quarter_severity.csv (primary time series, same coverage, coarser)
  - timeseries_year_severity.csv    (100% coverage, CCN-year fallback)
  - breakdown_age_band.csv
  - breakdown_impaired_speeding_ticket.csv
  - breakdown_ward.csv
  - breakdown_match_source.csv
  - quarterly_injuries_by_severity.png
  - DATA_NOTES.md (generated methodology + caveats, reflects the actual row
    counts from this run -- see README.md for the human-written overview)

Also reads (checked into data/reference/, not regenerated by this script --
see data/reference/SOURCES.md for full provenance):
  - ddot_monthly_scooter_ridership.csv
  - ride_report_quarterly_scooter_stats.csv

Usage:
    uv run fetch-crash-data   # populates data/raw/crash_details_table.csv
    uv run build-analysis     # this script
"""

import csv
import json
import re
import urllib.parse
import urllib.request
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_CSV = REPO_ROOT / "data" / "raw" / "crash_details_table.csv"
REFERENCE_DIR = REPO_ROOT / "data" / "reference"
OUTPUT_DIR = REPO_ROOT / "output"

FEATURE_SERVER_QUERY_URL = (
    "https://maps2.dcgis.dc.gov/dcgis/rest/services/"
    "DCGIS_DATA/Public_Safety_WebMercator/MapServer/24/query"
)
BATCH_SIZE = 200

# E-scooters (Bird/Skip/LimeBike) joined DC's dockless *bike* pilot (launched
# Sept 2017) in March 2018 -- confirmed by DDOT-coauthored research (Roshan
# Zamir et al. 2019, arXiv:1907.11526: "dockless scootershare [introduced] in
# early 2018", DC trip data collection starting March 2018) and contemporary
# reporting (Skip/Bird added scootershare, LimeBike added scooters to its
# fleet, March 2018). Exact day not documented; month-level is what the chart
# needs anyway. Anything dated before this is definitionally NOT a shared
# e-scooter -- DC had none yet.
SCOOTER_SHARE_DEBUT_MONTH = "2018-03"
# Earliest quarters (2003-Q4, 2006-Q3, then a gap to 2008-Q2) are sparse,
# isolated data points with multi-year gaps between them -- not a real
# reporting series. 2010-Q1 onward is contiguous, quarter over quarter, with
# no gaps through the present.
CHART_MIN_QUARTER = "2010-Q1"
RIDERSHIP_CSV = REFERENCE_DIR / "ddot_monthly_scooter_ridership.csv"
RIDE_REPORT_CSV = REFERENCE_DIR / "ride_report_quarterly_scooter_stats.csv"

MOPED_SCOOTER_RE = re.compile(r"moped/scooter", re.I)
AGE_BANDS = [
    (0, 16, "<16"),
    (16, 25, "16-24"),
    (25, 35, "25-34"),
    (35, 45, "35-44"),
    (45, 55, "45-54"),
    (55, 65, "55-64"),
    (65, 200, "65+"),
]


def match_source(invehicletype: str) -> str | None:
    t = (invehicletype or "").strip()
    if MOPED_SCOOTER_RE.search(t):
        return "moped_scooter"
    if t.lower() == "moped or motorized bicycle":
        return "moped_or_motorized_bicycle"
    return None


def severity_of(fatal: str, major: str, minor: str) -> str:
    if fatal == "Y":
        return "Fatal"
    if major == "Y":
        return "Major"
    if minor == "Y":
        return "Minor"
    return "None"


def quarter_of(year_month: str) -> str:
    year, month = year_month.split("-")
    q = (int(month) - 1) // 3 + 1
    return f"{year}-Q{q}"


def age_band_of(age: str) -> str:
    if not age:
        return "Unknown"
    try:
        a = int(float(age))
    except ValueError:
        return "Unknown"
    for lo, hi, label in AGE_BANDS:
        if lo <= a < hi:
            return label
    return "Unknown"


def load_scooter_rows() -> list[dict]:
    if not SOURCE_CSV.exists():
        raise SystemExit(
            f"{SOURCE_CSV.relative_to(REPO_ROOT)} not found. "
            f"Run `uv run fetch-crash-data` first."
        )
    rows = []
    with SOURCE_CSV.open(encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            src = match_source(row["INVEHICLETYPE"])
            if src is None:
                continue
            ccn = row["CCN"] or ""
            year_ccn = 2000 + int(ccn[:2]) if ccn[:2].isdigit() else None
            rows.append(
                {
                    "CRIMEID": row["CRIMEID"],
                    "CCN": ccn,
                    "PERSONID": row["PERSONID"],
                    "PERSONTYPE": row["PERSONTYPE"],
                    "AGE": row["AGE"],
                    "age_band": age_band_of(row["AGE"]),
                    "FATAL": row["FATAL"],
                    "MAJORINJURY": row["MAJORINJURY"],
                    "MINORINJURY": row["MINORINJURY"],
                    "severity": severity_of(
                        row["FATAL"], row["MAJORINJURY"], row["MINORINJURY"]
                    ),
                    "IMPAIRED": row["IMPAIRED"],
                    "SPEEDING": row["SPEEDING"],
                    "TICKETISSUED": row["TICKETISSUED"],
                    "INVEHICLETYPE": row["INVEHICLETYPE"],
                    "match_source": src,
                    "year_ccn": year_ccn,
                }
            )
    return rows


def fetch_crash_dates(crimeids: list[str]) -> dict[str, dict]:
    """Query DDOT's Crashes in DC layer in batches, keyed by CRIMEID."""
    result: dict[str, dict] = {}
    for i in range(0, len(crimeids), BATCH_SIZE):
        batch = crimeids[i : i + BATCH_SIZE]
        where = "CRIMEID IN (" + ",".join(f"'{cid}'" for cid in batch) + ")"
        params = urllib.parse.urlencode(
            {
                "where": where,
                "outFields": "CRIMEID,REPORTDATE,WARD",
                "f": "json",
                "resultRecordCount": BATCH_SIZE,
            }
        ).encode()
        req = urllib.request.Request(FEATURE_SERVER_QUERY_URL, data=params)
        with urllib.request.urlopen(req, timeout=30) as resp:
            payload = json.loads(resp.read())
        for feat in payload.get("features", []):
            attrs = feat["attributes"]
            cid = attrs["CRIMEID"]
            report_ms = attrs.get("REPORTDATE")
            dt = (
                datetime.fromtimestamp(report_ms / 1000, tz=timezone.utc)
                if report_ms
                else None
            )
            result[cid] = {
                "year": dt.year if dt else None,
                "year_month": dt.strftime("%Y-%m") if dt else None,
                "ward": attrs.get("WARD"),
            }
        print(f"  queried {i + len(batch)}/{len(crimeids)} CRIMEIDs, "
              f"{len(result)} resolved so far")
    return result


def enrich_with_dates(rows: list[dict]) -> None:
    unique_ids = sorted({r["CRIMEID"] for r in rows})
    print(f"Querying DDOT crash-location table for {len(unique_ids)} unique CRIMEIDs...")
    date_lookup = fetch_crash_dates(unique_ids)
    resolved = 0
    for r in rows:
        info = date_lookup.get(r["CRIMEID"])
        if info and info["year"]:
            r["year"] = info["year"]
            r["year_month"] = info["year_month"]
            r["ward"] = info["ward"]
            r["date_source"] = "reportdate"
            resolved += 1
        else:
            r["year"] = r["year_ccn"]
            r["year_month"] = None
            r["ward"] = None
            r["date_source"] = "ccn_year_fallback"
    print(
        f"Resolved REPORTDATE for {resolved}/{len(rows)} person-rows "
        f"({resolved / len(rows):.0%})"
    )


def write_csv(path: Path, fieldnames: list[str], data_rows: list[dict]) -> None:
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(data_rows)
    print(f"wrote {path.relative_to(REPO_ROOT)} ({len(data_rows)} rows)")


def write_person_level(rows: list[dict]) -> None:
    fieldnames = [
        "CRIMEID", "CCN", "PERSONID", "PERSONTYPE", "AGE", "age_band",
        "FATAL", "MAJORINJURY", "MINORINJURY", "severity",
        "IMPAIRED", "SPEEDING", "TICKETISSUED", "INVEHICLETYPE",
        "match_source", "year_ccn", "year", "year_month", "ward", "date_source",
    ]
    write_csv(OUTPUT_DIR / "person_level.csv", fieldnames, rows)


def write_timeseries_month(rows: list[dict]) -> None:
    counts = Counter(
        (r["year_month"], r["severity"]) for r in rows if r["year_month"]
    )
    out = [
        {"year_month": ym, "severity": sev, "count": n}
        for (ym, sev), n in sorted(counts.items())
    ]
    write_csv(OUTPUT_DIR / "timeseries_month_severity.csv", ["year_month", "severity", "count"], out)


def write_timeseries_quarter(rows: list[dict]) -> None:
    counts = Counter(
        (quarter_of(r["year_month"]), r["severity"]) for r in rows if r["year_month"]
    )
    out = [
        {"year_quarter": yq, "severity": sev, "count": n}
        for (yq, sev), n in sorted(counts.items())
    ]
    write_csv(
        OUTPUT_DIR / "timeseries_quarter_severity.csv",
        ["year_quarter", "severity", "count"],
        out,
    )


def write_timeseries_year(rows: list[dict]) -> None:
    counts = Counter((r["year"], r["severity"]) for r in rows)
    out = [
        {"year": yr, "severity": sev, "count": n}
        for (yr, sev), n in sorted(counts.items())
    ]
    write_csv(OUTPUT_DIR / "timeseries_year_severity.csv", ["year", "severity", "count"], out)


def write_breakdown_age(rows: list[dict]) -> None:
    counts = Counter((r["age_band"], r["severity"]) for r in rows)
    band_order = [b[2] for b in AGE_BANDS] + ["Unknown"]
    out = [
        {"age_band": band, "severity": sev, "count": counts[(band, sev)]}
        for band in band_order
        for sev in ["Fatal", "Major", "Minor", "None"]
        if counts[(band, sev)]
    ]
    write_csv(OUTPUT_DIR / "breakdown_age_band.csv", ["age_band", "severity", "count"], out)


def write_breakdown_flags(rows: list[dict]) -> None:
    out = []
    for flag_type, key in [
        ("impaired", "IMPAIRED"),
        ("speeding", "SPEEDING"),
        ("ticket_issued", "TICKETISSUED"),
    ]:
        counts = Counter((r[key], r["severity"]) for r in rows)
        for (flag_value, sev), n in sorted(counts.items()):
            out.append(
                {
                    "flag_type": flag_type,
                    "flag_value": flag_value,
                    "severity": sev,
                    "count": n,
                }
            )
    write_csv(
        OUTPUT_DIR / "breakdown_impaired_speeding_ticket.csv",
        ["flag_type", "flag_value", "severity", "count"],
        out,
    )


def write_breakdown_ward(rows: list[dict]) -> None:
    counts = Counter((r["ward"] or "Unknown/unmatched", r["severity"]) for r in rows)
    out = [
        {"ward": ward, "severity": sev, "count": n}
        for (ward, sev), n in sorted(counts.items())
    ]
    write_csv(OUTPUT_DIR / "breakdown_ward.csv", ["ward", "severity", "count"], out)


def write_breakdown_match_source(rows: list[dict]) -> None:
    counts = Counter((r["match_source"], r["year"]) for r in rows)
    out = [
        {"match_source": src, "year": yr, "count": n}
        for (src, yr), n in sorted(counts.items())
    ]
    write_csv(OUTPUT_DIR / "breakdown_match_source.csv", ["match_source", "year", "count"], out)


def load_ridership_by_quarter() -> dict[str, tuple[int, int]]:
    """Returns {year_quarter: (summed_rides, n_months_present)}. n_months_present
    < 3 flags a partial quarter (DDOT's series starts Jan 2019 and ends Feb 2022,
    so Q1 2022 only has 2 of its 3 months)."""
    if not RIDERSHIP_CSV.exists():
        return {}
    sums: dict[str, list] = defaultdict(lambda: [0, 0])
    with RIDERSHIP_CSV.open(newline="") as f:
        for row in csv.DictReader(f):
            yq = quarter_of(row["year_month"])
            sums[yq][0] += int(row["rides"])
            sums[yq][1] += 1
    return {yq: (total, n) for yq, (total, n) in sums.items()}


def load_ride_report_quarterly() -> dict[str, dict]:
    """Scraped from public.ridereport.com/dc (Scooters filter), per quarter.

    coverage_reliable=False for 2019-Q1..2021-Q3: cross-checked against DDOT's
    own published monthly ridership (ddot_monthly_scooter_ridership.csv) for
    the same quarters and found Ride Report capturing only ~2% of DDOT's trip
    count in 2019-Q1, rising to ~88% by 2021-Q3 and ~99% by 2021-Q4 -- a data
    *coverage* ramp-up as operators onboarded to Ride Report's feed, not real
    ~90x ridership growth. Using those early quarters at face value would
    fabricate a fake hockey-stick. Only reliable-flagged quarters are plotted.
    """
    if not RIDE_REPORT_CSV.exists():
        return {}
    out = {}
    with RIDE_REPORT_CSV.open(newline="") as f:
        for row in csv.DictReader(f):
            out[row["year_quarter"]] = {
                "total_trips": int(row["total_trips"]),
                "avg_vehicles": int(row["avg_vehicles"]) if row["avg_vehicles"] else None,
                "coverage_reliable": row["coverage_reliable"] == "True",
            }
    return out


def render_chart(rows: list[dict]) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    quarterly = defaultdict(lambda: defaultdict(int))
    quarters = set()
    for r in rows:
        if not r["year_month"]:
            continue
        yq = quarter_of(r["year_month"])
        quarterly[r["severity"]][yq] += 1
        quarters.add(yq)
    debut_quarter = quarter_of(SCOOTER_SHARE_DEBUT_MONTH)
    quarters.add(debut_quarter)  # make sure the marker is in-range

    ridership = load_ridership_by_quarter()
    ride_report = load_ride_report_quarterly()
    last_ddot_quarter = max(ridership) if ridership else None

    quarters |= ridership.keys()
    quarters |= {q for q, v in ride_report.items() if v["coverage_reliable"]}
    quarters = sorted(q for q in quarters if q >= CHART_MIN_QUARTER)

    severities = ["None", "Minor", "Major", "Fatal"]
    colors = {"None": "#c7c7c7", "Minor": "#f2b134", "Major": "#e8590c", "Fatal": "#a61e1e"}

    fig, ax = plt.subplots(figsize=(16, 6.5))
    bottom = [0] * len(quarters)
    for sev in severities:
        series = [quarterly[sev].get(q, 0) for q in quarters]
        ax.bar(quarters, series, bottom=bottom, label=sev, color=colors[sev], width=0.85)
        bottom = [b + s for b, s in zip(bottom, series)]

    ax.set_title("DC scooter-rider crash involvements by quarter and injury severity")
    ax.set_ylabel("Person-involvements")
    ax.set_xlabel(
        f"Quarter (REPORTDATE; excludes ~2% of rows with no resolvable date). "
        f"Pre-{CHART_MIN_QUARTER} excluded -- sparse, gapped reporting before then."
    )

    ax.axvline(x=debut_quarter, color="#1f6f43", linestyle="-", linewidth=1.5)
    ax.annotate(
        "shared e-scooters debut\nin DC (Mar 2018, within\nthis quarter) [before\nthis: not share-fleet]",
        xy=(debut_quarter, ax.get_ylim()[1] * 0.74),
        fontsize=8,
        ha="left",
        color="#1f6f43",
    )

    ax.axvline(x="2023-Q1", color="black", linestyle="--", linewidth=1)
    ax.annotate(
        "vehicle-type coding\nscheme changed here",
        xy=("2023-Q1", ax.get_ylim()[1] * 0.9),
        fontsize=8,
        ha="left",
    )

    if ridership or ride_report:
        ax2 = ax.twinx()

        # DDOT's own published series (authoritative where it exists)
        rider_series = [ridership.get(q) for q in quarters]
        xs = [q for q, v in zip(quarters, rider_series) if v is not None]
        ys = [v[0] for v in rider_series if v is not None]
        partial = [q for q, v in zip(quarters, rider_series) if v is not None and v[1] < 3]
        ax2.plot(xs, ys, color="#2f6fed", linewidth=2, marker="o", markersize=4,
                 label="Quarterly rides (DDOT)")
        if partial:
            ax2.scatter(
                partial, [ridership[q][0] for q in partial],
                facecolors="none", edgecolors="#2f6fed", s=80, linewidths=1.5, zorder=5,
                label="Partial quarter (<3 months)",
            )

        # Ride Report picks up strictly after DDOT's own series ends, and only
        # for quarters flagged reliable (see load_ride_report_quarterly) --
        # never spliced where it would overlap/replace a DDOT-reported quarter.
        rr_xs = [
            q for q in quarters
            if q in ride_report and ride_report[q]["coverage_reliable"]
            and (last_ddot_quarter is None or q > last_ddot_quarter)
        ]
        rr_ys = [ride_report[q]["total_trips"] for q in rr_xs]
        if rr_xs:
            ax2.plot(rr_xs, rr_ys, color="#8b2fed", linewidth=2, linestyle="--",
                     marker="s", markersize=4, label="Quarterly rides (Ride Report)")

        ax2.set_ylabel("Quarterly scooter rides", color="#2f6fed")
        ax2.tick_params(axis="y", labelcolor="#2f6fed")
        ax2.set_ylim(bottom=0)
        ax2.legend(loc="upper left", bbox_to_anchor=(0.0, 0.98), fontsize=8)

    ax.legend(title="Injury severity", loc="upper right")

    step = max(1, len(quarters) // 40)
    ax.set_xticks(quarters[::step])
    ax.set_xticklabels(quarters[::step], rotation=90, fontsize=7)
    fig.tight_layout()
    out_path = OUTPUT_DIR / "quarterly_injuries_by_severity.png"
    fig.savefig(out_path, dpi=150)
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")


def write_data_notes(rows: list[dict]) -> None:
    n = len(rows)
    by_source = Counter(r["match_source"] for r in rows)
    resolved = sum(1 for r in rows if r["date_source"] == "reportdate")
    fatal_n = sum(1 for r in rows if r["severity"] == "Fatal")
    major_n = sum(1 for r in rows if r["severity"] == "Major")
    minor_n = sum(1 for r in rows if r["severity"] == "Minor")
    none_n = sum(1 for r in rows if r["severity"] == "None")
    years = sorted({r["year"] for r in rows if r["year"]})

    text = f"""# Data notes (generated)

This file is regenerated by `build.py` on every run and reflects the actual
row counts from *this* run -- DC's crash data is live and grows over time, so
these numbers will drift from whatever is quoted in the top-level README or
any post that links here. See `../README.md` for the human-written overview.

Built from `data/raw/crash_details_table.csv` (DC MPD person-level crash
detail extract, fetched via `fetch_crash_data.py`) joined against DDOT's
"Crashes in DC" ArcGIS layer (CRIMEID -> REPORTDATE, WARD):
{FEATURE_SERVER_QUERY_URL}

## Scope

- **Population**: person-rows where the rider's own `INVEHICLETYPE` indicates
  a scooter/moped. This counts injuries *to scooter riders*, not third parties
  (e.g. a pedestrian struck by a scooter) -- the schema has no way to identify
  that from a rider's own row.
- **Total scooter-rider person-rows**: {n}
  - `moped_scooter` (covers 2008-2022): {by_source.get('moped_scooter', 0)}
  - `moped_or_motorized_bicycle` (covers 2023-{years[-1] if years else '?'}): {by_source.get('moped_or_motorized_bicycle', 0)}
- **Severity split**: Fatal {fatal_n}, Major {major_n}, Minor {minor_n}, None {none_n}

## Known data issues (do not silently ignore these)

1. **2023 coding-scheme seam.** DC's `INVEHICLETYPE` value for scooters/mopeds
   changed around 2023: `Moped/scooter` rows run 2008-2022 then stop entirely;
   `Moped or motorized bicycle` rows are near-zero through 2022 then take over
   from 2023 onward. Both are included here and tagged via `match_source` /
   `breakdown_match_source.csv` so this seam stays auditable. The 2023+ code
   is broader and may include some non-electric mopeds, so 2023+ counts may
   run slightly high relative to "true" e-scooter injuries.
2. **~{100 * (n - resolved) // n if n else 0}% of rows have no resolvable REPORTDATE.**
   DDOT's crash-location layer excludes crashes it couldn't geocode, so
   {n - resolved} of {n} rows fall back to a year-only date derived from the
   CCN case-number prefix (`date_source = ccn_year_fallback`). Use
   `timeseries_month_severity.csv` for month-level trend (covers the
   {resolved} resolved rows only) and `timeseries_year_severity.csv` when you
   need every row accounted for.
3. **Small-N severity bins.** Only {fatal_n} fatal rows total across the whole
   period -- do not read year-to-year wiggles in the fatal series as a trend.
4. **No scooter-share operator field exists anywhere in this data.**
   Operator-level slicing (Lime/Bird/Spin/etc.) is not possible from what's
   fetched here; it would require an external DDOT/operator-reported dataset.
5. **Counts are person-involvements, not unique crashes** -- a small number of
   crashes have more than one scooter-coded person (e.g. rider + passenger).
6. **Shared/dockless e-scooters still cannot be isolated from privately-owned
   or gig-delivery (DoorDash/Uber Eats-style) mopeds and scooters, even after
   the {SCOOTER_SHARE_DEBUT_MONTH} program-debut cutoff marked on the chart.**
   That marker is a hard floor (nothing before it can be a shared device --
   the program didn't exist), not a clean split going forward: `INVEHICLETYPE`
   is one blunt bucket covering shared-fleet devices, privately-owned kick
   scooters, and delivery-rider mopeds together, and no field in this data
   (including `LICENSEPLATESTATE`, which was tested and rejected -- it's
   noisy/inconsistently coded across years and "no plate" rows already appear
   throughout 2008-2016, before shared scooters existed) can split them apart.
   This confound is worst in exactly the 2020-2026 window this analysis cares
   about, coinciding with pandemic-era gig delivery growth.
7. **Ride Report's historical numbers are unreliable before 2021-Q4.**
   Cross-checked against DDOT's own published monthly ridership for the
   overlapping period: Ride Report captured only ~2% of DDOT's trip count in
   2019-Q1, rising to ~34% by 2021-Q1, ~88% by 2021-Q3, and ~99% by 2021-Q4.
   That's a data-coverage ramp-up (operators progressively onboarding to Ride
   Report's feed), not real ~90x ridership growth -- DDOT's own numbers show
   growth over that period was closer to 2x. Only 2021-Q4 onward is used
   anywhere in this analysis; earlier Ride Report quarters are kept in
   `data/reference/ride_report_quarterly_scooter_stats.csv` for transparency
   but marked `coverage_reliable=False` and excluded from every chart/aggregate.
8. **Chart starts at {CHART_MIN_QUARTER}, not the earliest data.** The full
   crash history has scattered points back to 2003 (2003-Q4, 2006-Q3, then a
   gap to 2008-Q2), with multi-year gaps between them -- not a real
   quarter-over-quarter series. 2010-Q1 onward has no gaps through the
   present, so the chart is clipped there for a clean, continuous x-axis;
   `timeseries_quarter_severity.csv` still has the full history back to 2003
   if you want it.

## Files in output/

- `person_level.csv` -- one row per scooter-rider person-record; the base
  dataset everything else rolls up from.
- `timeseries_quarter_severity.csv` -- primary time series for graphing
  (matches the chart's binning; same REPORTDATE coverage as the monthly file).
- `timeseries_month_severity.csv` -- finer-grained companion series, same
  ~98% REPORTDATE coverage, monthly instead of quarterly.
- `timeseries_year_severity.csv` -- coarsest, 100%-coverage companion series.
- `breakdown_age_band.csv`, `breakdown_impaired_speeding_ticket.csv`,
  `breakdown_ward.csv`, `breakdown_match_source.csv` -- other slicing
  dimensions found in the data.
- `quarterly_injuries_by_severity.png` -- stacked bar chart of the primary
  time series from {CHART_MIN_QUARTER} onward (earlier quarters excluded --
  sparse, gapped reporting before then, see caveat 8 above), with the
  {SCOOTER_SHARE_DEBUT_MONTH} program-debut quarter and the 2023
  coding-scheme seam both marked, and ridership overlaid (right axis) --
  DDOT's own series through 2022-Q1, Ride Report spliced on from 2022-Q2
  onward (reliable quarters only), each visually distinguished.
"""
    (OUTPUT_DIR / "DATA_NOTES.md").write_text(text)
    print(f"wrote {(OUTPUT_DIR / 'DATA_NOTES.md').relative_to(REPO_ROOT)}")


def main() -> None:
    OUTPUT_DIR.mkdir(exist_ok=True)
    print(f"Reading {SOURCE_CSV.relative_to(REPO_ROOT)} ...")
    rows = load_scooter_rows()
    print(f"Found {len(rows)} scooter-rider person-rows "
          f"({len({r['CRIMEID'] for r in rows})} unique CRIMEIDs)")

    enrich_with_dates(rows)

    write_person_level(rows)
    write_timeseries_month(rows)
    write_timeseries_quarter(rows)
    write_timeseries_year(rows)
    write_breakdown_age(rows)
    write_breakdown_flags(rows)
    write_breakdown_ward(rows)
    write_breakdown_match_source(rows)
    render_chart(rows)
    write_data_notes(rows)


if __name__ == "__main__":
    main()
